//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeRatings
    {
        public AgeRatings()
        {
            this.Movies = new HashSet<Movies>();
        }
    
        public int Id { get; set; }
        public int Age { get; set; }
    
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
