//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int UserClientId { get; set; }
        public int UserMasterId { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int PaymentMethodId { get; set; }
        public string Comment { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
