//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentSchedules
    {
        public int Id { get; set; }
        public int MasterServiceId { get; set; }
        public int DayOfWeekId { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual DaysOfWeek DaysOfWeek { get; set; }
        public virtual MasterServices MasterServices { get; set; }
    }
}
