//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class assembly_
    {
        public assembly_()
        {
            this.partassembly_ = new HashSet<partassembly_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
    
        public virtual ICollection<partassembly_> partassembly_ { get; set; }
    }
}
