//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartProducts
    {
        public int CartProductId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
