//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class casesize_
    {
        public casesize_()
        {
            this.case_ = new HashSet<case_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<case_> case_ { get; set; }
    }
}
