//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate_
    {
        public certificate_()
        {
            this.powersupply_ = new HashSet<powersupply_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<powersupply_> powersupply_ { get; set; }
    }
}
