//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public int FilmID { get; set; }
        public string Name { get; set; }
        public float Rating { get; set; }
        public System.DateTime StartDate { get; set; }
        public int AgeRating { get; set; }
        public string Cover { get; set; }
    }
}
