//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class formfactor_
    {
        public formfactor_()
        {
            this.boardformfactorcase_ = new HashSet<boardformfactorcase_>();
            this.motherboard_ = new HashSet<motherboard_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<boardformfactorcase_> boardformfactorcase_ { get; set; }
        public virtual ICollection<motherboard_> motherboard_ { get; set; }
    }
}
