//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gpuinterface_
    {
        public gpuinterface_()
        {
            this.gpu_ = new HashSet<gpu_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<gpu_> gpu_ { get; set; }
    }
}
