//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halls
    {
        public Halls()
        {
            this.Seats = new HashSet<Seats>();
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClassificationId { get; set; }
    
        public virtual Classifications Classifications { get; set; }
        public virtual ICollection<Seats> Seats { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
