//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class memorytype_
    {
        public memorytype_()
        {
            this.motherboard_ = new HashSet<motherboard_>();
            this.ram_ = new HashSet<ram_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<motherboard_> motherboard_ { get; set; }
        public virtual ICollection<ram_> ram_ { get; set; }
    }
}
