//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_pr15Entities : DbContext
    {
        public DB_pr15Entities()
            : base("name=DB_pr15Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<assembly_> assembly_ { get; set; }
        public DbSet<basepart_> basepart_ { get; set; }
        public DbSet<boardformfactorcase_> boardformfactorcase_ { get; set; }
        public DbSet<case_> case_ { get; set; }
        public DbSet<casesize_> casesize_ { get; set; }
        public DbSet<certificate_> certificate_ { get; set; }
        public DbSet<cpu_> cpu_ { get; set; }
        public DbSet<fandimension_> fandimension_ { get; set; }
        public DbSet<formfactor_> formfactor_ { get; set; }
        public DbSet<gpu_> gpu_ { get; set; }
        public DbSet<gpuinterface_> gpuinterface_ { get; set; }
        public DbSet<hdd_> hdd_ { get; set; }
        public DbSet<igpu_> igpu_ { get; set; }
        public DbSet<manufacturer_> manufacturer_ { get; set; }
        public DbSet<memorytype_> memorytype_ { get; set; }
        public DbSet<motherboard_> motherboard_ { get; set; }
        public DbSet<partassembly_> partassembly_ { get; set; }
        public DbSet<parttype_> parttype_ { get; set; }
        public DbSet<powersupply_> powersupply_ { get; set; }
        public DbSet<processorcooler_> processorcooler_ { get; set; }
        public DbSet<ram_> ram_ { get; set; }
        public DbSet<socket_> socket_ { get; set; }
        public DbSet<socketprocessorcooler_> socketprocessorcooler_ { get; set; }
        public DbSet<ssd_> ssd_ { get; set; }
        public DbSet<storagedevice_> storagedevice_ { get; set; }
        public DbSet<storagedeviceinterface_> storagedeviceinterface_ { get; set; }
        public DbSet<storagedevicetype_> storagedevicetype_ { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<videoconnector_> videoconnector_ { get; set; }
        public DbSet<videoconnectorgpu_> videoconnectorgpu_ { get; set; }
    }
}
