//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.Sessions = new HashSet<Sessions>();
            this.Genres = new HashSet<Genres>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Rating { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int AgeRatingId { get; set; }
        public string PosterPath { get; set; }
    
        public virtual AgeRatings AgeRatings { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
        public virtual ICollection<Genres> Genres { get; set; }
    }
}
