//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.CartProducts = new HashSet<CartProducts>();
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<CartProducts> CartProducts { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
    }
}
