//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public Seats()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public int HallId { get; set; }
        public int Row { get; set; }
        public int Number { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
