//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class socket_
    {
        public socket_()
        {
            this.cpu_ = new HashSet<cpu_>();
            this.motherboard_ = new HashSet<motherboard_>();
            this.socketprocessorcooler_ = new HashSet<socketprocessorcooler_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<cpu_> cpu_ { get; set; }
        public virtual ICollection<motherboard_> motherboard_ { get; set; }
        public virtual ICollection<socketprocessorcooler_> socketprocessorcooler_ { get; set; }
    }
}
