//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class storagedevicetype_
    {
        public storagedevicetype_()
        {
            this.storagedevice_ = new HashSet<storagedevice_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<storagedevice_> storagedevice_ { get; set; }
    }
}
