//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoconnector_
    {
        public videoconnector_()
        {
            this.videoconnectorgpu_ = new HashSet<videoconnectorgpu_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<videoconnectorgpu_> videoconnectorgpu_ { get; set; }
    }
}
